# .golangci.yml
version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - revive
    - ineffassign
    - unused
    - errcheck
    - gosec
    - nilerr
    - unparam

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/rudolfkova/grpc_auth   # ← обязательно свой module path!

issues:
  max-issues-per-linter: 0
  max-same-issues: 0