.PHONY: build
build-auth:
	go build -v ./auth-service/cmd/auth-service


.PHONY: start
start-auth:
	./auth-service.exe -config-path=config.toml

.PHONY: lint
lint-auth:
	golangci-lint run ./auth-service/...

.PHONY: migrate
migrate-up:
	migrate -path auth-service/migrations -database "$(DB_DSN)" up

.PHONY: gen-auth
gen-auth:
	protoc -I auth-service \
	  --go_out=auth-service --go_opt=paths=source_relative \
	  --go-grpc_out=auth-service --go-grpc_opt=paths=source_relative \
	  auth-service/proto/auth/v1/auth.proto

.PHONY: tidy
tidy-auth:
	cd auth-service && go mod tidy

.PHONY: gofmt
gofmt:
	gofmt -w -s .

.PHONY: test
test-auth:
	cd auth-service && go test -v -race -timeout 30s ./...
test-auth-integration:
	cd auth-service && go test ./... -tags=integration -v

.PHONY: mocks
mocks-auth:
	cd auth-service && mockery --name=Auth --dir=./internal/grpc/auth --output=./mocks/auth --outpkg=mocks
	cd auth-service && mockery --name=UserRepository --dir=./internal/repository --output=./mocks/repository --outpkg=mocks
	cd auth-service && mockery --name=SessionRepository --dir=./internal/repository --output=./mocks/repository --outpkg=mocks
	cd auth-service && mockery --name=Cache --dir=./internal/repository --output=./mocks/repository --outpkg=mocks
	cd auth-service && mockery --name=TokenProvider --dir=./provider --output=./mocks/provider --outpkg=mocks
	cd auth-service && mockery --name=AuthServiceServer --dir=./proto/auth/v1 --output=./mocks/proto/auth/v1 --outpkg=mocks
	cd auth-service && mockery --name=AuthServiceClient --dir=./proto/auth/v1 --output=./mocks/proto/auth/v1 --outpkg=mocks
	cd auth-service && mockery --name=UnsafeAuthServiceServer --dir=./proto/auth/v1 --output=./mocks/proto/auth/v1 --outpkg=mocks