database_url = "postgres://messenger:messenger@postgres:5432/auth_db?sslmode=disable"
test_database_url = "postgres://messenger:messenger@postgres:5432/auth_db?sslmode=disable"
redis_addr = "redis:6379"
test_redis_addr = "redis:6379"
bind_addr = ":50051"
access_token_ttl = "15m"
refresh_token_ttl = "720h"
log_level = "DEBUG"
jwt_secret = "123"
