// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	authv1 "auth/proto/auth/v1"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthServiceServer is an autogenerated mock type for the AuthServiceServer type
type AuthServiceServer struct {
	mock.Mock
}

// IsAdmin provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) IsAdmin(_a0 context.Context, _a1 *authv1.IsAdminRequest) (*authv1.IsAdminResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IsAdmin")
	}

	var r0 *authv1.IsAdminResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.IsAdminRequest) (*authv1.IsAdminResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.IsAdminRequest) *authv1.IsAdminResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.IsAdminResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.IsAdminRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) Login(_a0 context.Context, _a1 *authv1.LoginRequest) (*authv1.LoginResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *authv1.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LoginRequest) (*authv1.LoginResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LoginRequest) *authv1.LoginResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.LoginRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) Logout(_a0 context.Context, _a1 *authv1.LogoutRequest) (*authv1.LogoutResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 *authv1.LogoutResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LogoutRequest) (*authv1.LogoutResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LogoutRequest) *authv1.LogoutResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.LogoutResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.LogoutRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshToken provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) RefreshToken(_a0 context.Context, _a1 *authv1.RefreshTokenRequest) (*authv1.RefreshTokenResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *authv1.RefreshTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RefreshTokenRequest) (*authv1.RefreshTokenResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RefreshTokenRequest) *authv1.RefreshTokenResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.RefreshTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.RefreshTokenRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) Register(_a0 context.Context, _a1 *authv1.RegisterRequest) (*authv1.RegisterResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *authv1.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RegisterRequest) (*authv1.RegisterResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RegisterRequest) *authv1.RegisterResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.RegisterRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedAuthServiceServer provides a mock function with no fields
func (_m *AuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {
	_m.Called()
}

// NewAuthServiceServer creates a new instance of AuthServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceServer {
	mock := &AuthServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
