// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAuthServiceServer is an autogenerated mock type for the UnsafeAuthServiceServer type
type UnsafeAuthServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAuthServiceServer provides a mock function with no fields
func (_m *UnsafeAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {
	_m.Called()
}

// NewUnsafeAuthServiceServer creates a new instance of UnsafeAuthServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeAuthServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeAuthServiceServer {
	mock := &UnsafeAuthServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
