// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/character/v1/character.proto

package characterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Character struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Version       int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,8,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,9,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_proto_character_v1_character_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{0}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Character) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Character) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Character) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Character) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Character) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Character) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Character) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Character) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type ResolvePlayCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePlayCharacterRequest) Reset() {
	*x = ResolvePlayCharacterRequest{}
	mi := &file_proto_character_v1_character_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePlayCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePlayCharacterRequest) ProtoMessage() {}

func (x *ResolvePlayCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePlayCharacterRequest.ProtoReflect.Descriptor instead.
func (*ResolvePlayCharacterRequest) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{1}
}

func (x *ResolvePlayCharacterRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ResolvePlayCharacterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResolvePlayCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persisted     bool                   `protobuf:"varint,1,opt,name=persisted,proto3" json:"persisted,omitempty"`
	Character     *Character             `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePlayCharacterResponse) Reset() {
	*x = ResolvePlayCharacterResponse{}
	mi := &file_proto_character_v1_character_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePlayCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePlayCharacterResponse) ProtoMessage() {}

func (x *ResolvePlayCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePlayCharacterResponse.ProtoReflect.Descriptor instead.
func (*ResolvePlayCharacterResponse) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{2}
}

func (x *ResolvePlayCharacterResponse) GetPersisted() bool {
	if x != nil {
		return x.Persisted
	}
	return false
}

func (x *ResolvePlayCharacterResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type GetCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterRequest) Reset() {
	*x = GetCharacterRequest{}
	mi := &file_proto_character_v1_character_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterRequest) ProtoMessage() {}

func (x *GetCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterRequest) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{3}
}

func (x *GetCharacterRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetCharacterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterResponse) Reset() {
	*x = GetCharacterResponse{}
	mi := &file_proto_character_v1_character_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterResponse) ProtoMessage() {}

func (x *GetCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterResponse.ProtoReflect.Descriptor instead.
func (*GetCharacterResponse) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{4}
}

func (x *GetCharacterResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type GetCharacterByDisplayNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterByDisplayNameRequest) Reset() {
	*x = GetCharacterByDisplayNameRequest{}
	mi := &file_proto_character_v1_character_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterByDisplayNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterByDisplayNameRequest) ProtoMessage() {}

func (x *GetCharacterByDisplayNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterByDisplayNameRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterByDisplayNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{5}
}

func (x *GetCharacterByDisplayNameRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetCharacterByDisplayNameRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type GetCharacterByDisplayNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterByDisplayNameResponse) Reset() {
	*x = GetCharacterByDisplayNameResponse{}
	mi := &file_proto_character_v1_character_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterByDisplayNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterByDisplayNameResponse) ProtoMessage() {}

func (x *GetCharacterByDisplayNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterByDisplayNameResponse.ProtoReflect.Descriptor instead.
func (*GetCharacterByDisplayNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{6}
}

func (x *GetCharacterByDisplayNameResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type ListCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersRequest) Reset() {
	*x = ListCharactersRequest{}
	mi := &file_proto_character_v1_character_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersRequest) ProtoMessage() {}

func (x *ListCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersRequest.ProtoReflect.Descriptor instead.
func (*ListCharactersRequest) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{7}
}

func (x *ListCharactersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListCharactersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCharactersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListCharactersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*Character           `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersResponse) Reset() {
	*x = ListCharactersResponse{}
	mi := &file_proto_character_v1_character_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersResponse) ProtoMessage() {}

func (x *ListCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersResponse.ProtoReflect.Descriptor instead.
func (*ListCharactersResponse) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{8}
}

func (x *ListCharactersResponse) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

type CreateCharacterRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Пусто — сервер сгенерирует UUID.
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Data          []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	SchemaVersion int32  `protobuf:"varint,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_proto_character_v1_character_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCharacterRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCharacterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateCharacterRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateCharacterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCharacterRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateCharacterRequest) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

type CreateCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterResponse) Reset() {
	*x = CreateCharacterResponse{}
	mi := &file_proto_character_v1_character_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterResponse) ProtoMessage() {}

func (x *CreateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterResponse.ProtoReflect.Descriptor instead.
func (*CreateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCharacterResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type ReplaceCharacterDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// 0 — не проверять версию (как в world-service).
	ExpectedVersion int64 `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplaceCharacterDataRequest) Reset() {
	*x = ReplaceCharacterDataRequest{}
	mi := &file_proto_character_v1_character_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceCharacterDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceCharacterDataRequest) ProtoMessage() {}

func (x *ReplaceCharacterDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceCharacterDataRequest.ProtoReflect.Descriptor instead.
func (*ReplaceCharacterDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{11}
}

func (x *ReplaceCharacterDataRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReplaceCharacterDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReplaceCharacterDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReplaceCharacterDataRequest) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ReplaceCharacterDataRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type ReplaceCharacterDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceCharacterDataResponse) Reset() {
	*x = ReplaceCharacterDataResponse{}
	mi := &file_proto_character_v1_character_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceCharacterDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceCharacterDataResponse) ProtoMessage() {}

func (x *ReplaceCharacterDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceCharacterDataResponse.ProtoReflect.Descriptor instead.
func (*ReplaceCharacterDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{12}
}

func (x *ReplaceCharacterDataResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type DeleteCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterRequest) Reset() {
	*x = DeleteCharacterRequest{}
	mi := &file_proto_character_v1_character_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterRequest) ProtoMessage() {}

func (x *DeleteCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterRequest.ProtoReflect.Descriptor instead.
func (*DeleteCharacterRequest) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCharacterRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteCharacterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterResponse) Reset() {
	*x = DeleteCharacterResponse{}
	mi := &file_proto_character_v1_character_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterResponse) ProtoMessage() {}

func (x *DeleteCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_character_v1_character_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterResponse.ProtoReflect.Descriptor instead.
func (*DeleteCharacterResponse) Descriptor() ([]byte, []int) {
	return file_proto_character_v1_character_proto_rawDescGZIP(), []int{14}
}

var File_proto_character_v1_character_proto protoreflect.FileDescriptor

const file_proto_character_v1_character_proto_rawDesc = "" +
	"\n" +
	"\"proto/character/v1/character.proto\x12\fcharacter.v1\"\x9e\x02\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\x05R\rschemaVersion\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12&\n" +
	"\x0fcreated_at_unix\x18\b \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\t \x01(\x03R\rupdatedAtUnix\"F\n" +
	"\x1bResolvePlayCharacterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"s\n" +
	"\x1cResolvePlayCharacterResponse\x12\x1c\n" +
	"\tpersisted\x18\x01 \x01(\bR\tpersisted\x125\n" +
	"\tcharacter\x18\x02 \x01(\v2\x17.character.v1.CharacterR\tcharacter\">\n" +
	"\x13GetCharacterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"M\n" +
	"\x14GetCharacterResponse\x125\n" +
	"\tcharacter\x18\x01 \x01(\v2\x17.character.v1.CharacterR\tcharacter\"^\n" +
	" GetCharacterByDisplayNameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"Z\n" +
	"!GetCharacterByDisplayNameResponse\x125\n" +
	"\tcharacter\x18\x01 \x01(\v2\x17.character.v1.CharacterR\tcharacter\"^\n" +
	"\x15ListCharactersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"Q\n" +
	"\x16ListCharactersResponse\x127\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x17.character.v1.CharacterR\n" +
	"characters\"\xc1\x01\n" +
	"\x16CreateCharacterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\x05R\rschemaVersion\"P\n" +
	"\x17CreateCharacterResponse\x125\n" +
	"\tcharacter\x18\x01 \x01(\v2\x17.character.v1.CharacterR\tcharacter\"\xac\x01\n" +
	"\x1bReplaceCharacterDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\x05R\rschemaVersion\x12)\n" +
	"\x10expected_version\x18\x05 \x01(\x03R\x0fexpectedVersion\"U\n" +
	"\x1cReplaceCharacterDataResponse\x125\n" +
	"\tcharacter\x18\x01 \x01(\v2\x17.character.v1.CharacterR\tcharacter\"A\n" +
	"\x16DeleteCharacterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x19\n" +
	"\x17DeleteCharacterResponse2\xe2\x05\n" +
	"\x10CharacterService\x12m\n" +
	"\x14ResolvePlayCharacter\x12).character.v1.ResolvePlayCharacterRequest\x1a*.character.v1.ResolvePlayCharacterResponse\x12U\n" +
	"\fGetCharacter\x12!.character.v1.GetCharacterRequest\x1a\".character.v1.GetCharacterResponse\x12|\n" +
	"\x19GetCharacterByDisplayName\x12..character.v1.GetCharacterByDisplayNameRequest\x1a/.character.v1.GetCharacterByDisplayNameResponse\x12[\n" +
	"\x0eListCharacters\x12#.character.v1.ListCharactersRequest\x1a$.character.v1.ListCharactersResponse\x12^\n" +
	"\x0fCreateCharacter\x12$.character.v1.CreateCharacterRequest\x1a%.character.v1.CreateCharacterResponse\x12m\n" +
	"\x14ReplaceCharacterData\x12).character.v1.ReplaceCharacterDataRequest\x1a*.character.v1.ReplaceCharacterDataResponse\x12^\n" +
	"\x0fDeleteCharacter\x12$.character.v1.DeleteCharacterRequest\x1a%.character.v1.DeleteCharacterResponseB*Z(character/proto/character/v1;characterv1b\x06proto3"

var (
	file_proto_character_v1_character_proto_rawDescOnce sync.Once
	file_proto_character_v1_character_proto_rawDescData []byte
)

func file_proto_character_v1_character_proto_rawDescGZIP() []byte {
	file_proto_character_v1_character_proto_rawDescOnce.Do(func() {
		file_proto_character_v1_character_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_character_v1_character_proto_rawDesc), len(file_proto_character_v1_character_proto_rawDesc)))
	})
	return file_proto_character_v1_character_proto_rawDescData
}

var file_proto_character_v1_character_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_character_v1_character_proto_goTypes = []any{
	(*Character)(nil),                         // 0: character.v1.Character
	(*ResolvePlayCharacterRequest)(nil),       // 1: character.v1.ResolvePlayCharacterRequest
	(*ResolvePlayCharacterResponse)(nil),      // 2: character.v1.ResolvePlayCharacterResponse
	(*GetCharacterRequest)(nil),               // 3: character.v1.GetCharacterRequest
	(*GetCharacterResponse)(nil),              // 4: character.v1.GetCharacterResponse
	(*GetCharacterByDisplayNameRequest)(nil),  // 5: character.v1.GetCharacterByDisplayNameRequest
	(*GetCharacterByDisplayNameResponse)(nil), // 6: character.v1.GetCharacterByDisplayNameResponse
	(*ListCharactersRequest)(nil),             // 7: character.v1.ListCharactersRequest
	(*ListCharactersResponse)(nil),            // 8: character.v1.ListCharactersResponse
	(*CreateCharacterRequest)(nil),            // 9: character.v1.CreateCharacterRequest
	(*CreateCharacterResponse)(nil),           // 10: character.v1.CreateCharacterResponse
	(*ReplaceCharacterDataRequest)(nil),       // 11: character.v1.ReplaceCharacterDataRequest
	(*ReplaceCharacterDataResponse)(nil),      // 12: character.v1.ReplaceCharacterDataResponse
	(*DeleteCharacterRequest)(nil),            // 13: character.v1.DeleteCharacterRequest
	(*DeleteCharacterResponse)(nil),           // 14: character.v1.DeleteCharacterResponse
}
var file_proto_character_v1_character_proto_depIdxs = []int32{
	0,  // 0: character.v1.ResolvePlayCharacterResponse.character:type_name -> character.v1.Character
	0,  // 1: character.v1.GetCharacterResponse.character:type_name -> character.v1.Character
	0,  // 2: character.v1.GetCharacterByDisplayNameResponse.character:type_name -> character.v1.Character
	0,  // 3: character.v1.ListCharactersResponse.characters:type_name -> character.v1.Character
	0,  // 4: character.v1.CreateCharacterResponse.character:type_name -> character.v1.Character
	0,  // 5: character.v1.ReplaceCharacterDataResponse.character:type_name -> character.v1.Character
	1,  // 6: character.v1.CharacterService.ResolvePlayCharacter:input_type -> character.v1.ResolvePlayCharacterRequest
	3,  // 7: character.v1.CharacterService.GetCharacter:input_type -> character.v1.GetCharacterRequest
	5,  // 8: character.v1.CharacterService.GetCharacterByDisplayName:input_type -> character.v1.GetCharacterByDisplayNameRequest
	7,  // 9: character.v1.CharacterService.ListCharacters:input_type -> character.v1.ListCharactersRequest
	9,  // 10: character.v1.CharacterService.CreateCharacter:input_type -> character.v1.CreateCharacterRequest
	11, // 11: character.v1.CharacterService.ReplaceCharacterData:input_type -> character.v1.ReplaceCharacterDataRequest
	13, // 12: character.v1.CharacterService.DeleteCharacter:input_type -> character.v1.DeleteCharacterRequest
	2,  // 13: character.v1.CharacterService.ResolvePlayCharacter:output_type -> character.v1.ResolvePlayCharacterResponse
	4,  // 14: character.v1.CharacterService.GetCharacter:output_type -> character.v1.GetCharacterResponse
	6,  // 15: character.v1.CharacterService.GetCharacterByDisplayName:output_type -> character.v1.GetCharacterByDisplayNameResponse
	8,  // 16: character.v1.CharacterService.ListCharacters:output_type -> character.v1.ListCharactersResponse
	10, // 17: character.v1.CharacterService.CreateCharacter:output_type -> character.v1.CreateCharacterResponse
	12, // 18: character.v1.CharacterService.ReplaceCharacterData:output_type -> character.v1.ReplaceCharacterDataResponse
	14, // 19: character.v1.CharacterService.DeleteCharacter:output_type -> character.v1.DeleteCharacterResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_character_v1_character_proto_init() }
func file_proto_character_v1_character_proto_init() {
	if File_proto_character_v1_character_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_character_v1_character_proto_rawDesc), len(file_proto_character_v1_character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_character_v1_character_proto_goTypes,
		DependencyIndexes: file_proto_character_v1_character_proto_depIdxs,
		MessageInfos:      file_proto_character_v1_character_proto_msgTypes,
	}.Build()
	File_proto_character_v1_character_proto = out.File
	file_proto_character_v1_character_proto_goTypes = nil
	file_proto_character_v1_character_proto_depIdxs = nil
}
