// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "auth/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// DelSession provides a mock function with given fields: keyID
func (_m *Cache) DelSession(keyID int) error {
	ret := _m.Called(keyID)

	if len(ret) == 0 {
		panic("no return value specified for DelSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(keyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSession provides a mock function with given fields: keyID
func (_m *Cache) GetSession(keyID int) (domain.Session, error) {
	ret := _m.Called(keyID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (domain.Session, error)); ok {
		return rf(keyID)
	}
	if rf, ok := ret.Get(0).(func(int) domain.Session); ok {
		r0 = rf(keyID)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(keyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetSession provides a mock function with given fields: keyID, value
func (_m *Cache) SetSession(keyID int, value domain.Session) error {
	ret := _m.Called(keyID, value)

	if len(ret) == 0 {
		panic("no return value specified for SetSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.Session) error); ok {
		r0 = rf(keyID, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
