// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "auth/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

// CreateSession provides a mock function with given fields: ctx, userID, appID, refreshToken, refExpiresAt
func (_m *SessionRepository) CreateSession(ctx context.Context, userID int, appID int, refreshToken string, refExpiresAt time.Time) (int, error) {
	ret := _m.Called(ctx, userID, appID, refreshToken, refExpiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, time.Time) (int, error)); ok {
		return rf(ctx, userID, appID, refreshToken, refExpiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, time.Time) int); ok {
		r0 = rf(ctx, userID, appID, refreshToken, refExpiresAt)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, time.Time) error); ok {
		r1 = rf(ctx, userID, appID, refreshToken, refExpiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeByRefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *SessionRepository) RevokeByRefreshToken(ctx context.Context, refreshToken string) (bool, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByRefreshToken")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionByID provides a mock function with given fields: ctx, id
func (_m *SessionRepository) SessionByID(ctx context.Context, id int) (domain.Session, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SessionByID")
	}

	var r0 domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.Session, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.Session); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionByRefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *SessionRepository) SessionByRefreshToken(ctx context.Context, refreshToken string) (domain.Session, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for SessionByRefreshToken")
	}

	var r0 domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Session, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Session); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
