// Package chaterror ...
package chaterror

import "errors"

var (
	// ErrUnauthenticated ...
	ErrUnauthenticated = errors.New("unauthenticated")
	// ErrPermissionDenied ...
	ErrPermissionDenied = errors.New("permission denied")
	// ErrChatNotFound ...
	ErrChatNotFound = errors.New("chat not found")
)
