// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/world/v1/world.proto

package worldv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type World struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Snapshot      []byte                 `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Version       int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	// Unix seconds UTC
	CreatedAtUnix int64 `protobuf:"varint,7,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64 `protobuf:"varint,8,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *World) Reset() {
	*x = World{}
	mi := &file_proto_world_v1_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *World) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*World) ProtoMessage() {}

func (x *World) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use World.ProtoReflect.Descriptor instead.
func (*World) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{0}
}

func (x *World) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *World) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *World) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *World) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *World) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *World) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *World) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *World) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type CreateWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Snapshot      []byte                 `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorldRequest) Reset() {
	*x = CreateWorldRequest{}
	mi := &file_proto_world_v1_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorldRequest) ProtoMessage() {}

func (x *CreateWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorldRequest.ProtoReflect.Descriptor instead.
func (*CreateWorldRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorldRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateWorldRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorldRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWorldRequest) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *CreateWorldRequest) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

type CreateWorldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	World         *World                 `protobuf:"bytes,1,opt,name=world,proto3" json:"world,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorldResponse) Reset() {
	*x = CreateWorldResponse{}
	mi := &file_proto_world_v1_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorldResponse) ProtoMessage() {}

func (x *CreateWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorldResponse.ProtoReflect.Descriptor instead.
func (*CreateWorldResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWorldResponse) GetWorld() *World {
	if x != nil {
		return x.World
	}
	return nil
}

type GetWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorldRequest) Reset() {
	*x = GetWorldRequest{}
	mi := &file_proto_world_v1_world_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorldRequest) ProtoMessage() {}

func (x *GetWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorldRequest.ProtoReflect.Descriptor instead.
func (*GetWorldRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorldRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWorldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	World         *World                 `protobuf:"bytes,1,opt,name=world,proto3" json:"world,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorldResponse) Reset() {
	*x = GetWorldResponse{}
	mi := &file_proto_world_v1_world_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorldResponse) ProtoMessage() {}

func (x *GetWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorldResponse.ProtoReflect.Descriptor instead.
func (*GetWorldResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorldResponse) GetWorld() *World {
	if x != nil {
		return x.World
	}
	return nil
}

type GetWorldByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorldByNameRequest) Reset() {
	*x = GetWorldByNameRequest{}
	mi := &file_proto_world_v1_world_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorldByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorldByNameRequest) ProtoMessage() {}

func (x *GetWorldByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorldByNameRequest.ProtoReflect.Descriptor instead.
func (*GetWorldByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorldByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetWorldByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	World         *World                 `protobuf:"bytes,1,opt,name=world,proto3" json:"world,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorldByNameResponse) Reset() {
	*x = GetWorldByNameResponse{}
	mi := &file_proto_world_v1_world_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorldByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorldByNameResponse) ProtoMessage() {}

func (x *GetWorldByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorldByNameResponse.ProtoReflect.Descriptor instead.
func (*GetWorldByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorldByNameResponse) GetWorld() *World {
	if x != nil {
		return x.World
	}
	return nil
}

type ReplaceWorldSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Snapshot      []byte                 `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// 0 — не проверять версию; иначе optimistic lock
	ExpectedVersion int64 `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplaceWorldSnapshotRequest) Reset() {
	*x = ReplaceWorldSnapshotRequest{}
	mi := &file_proto_world_v1_world_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceWorldSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceWorldSnapshotRequest) ProtoMessage() {}

func (x *ReplaceWorldSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceWorldSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ReplaceWorldSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{7}
}

func (x *ReplaceWorldSnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReplaceWorldSnapshotRequest) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ReplaceWorldSnapshotRequest) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ReplaceWorldSnapshotRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type ReplaceWorldSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	World         *World                 `protobuf:"bytes,1,opt,name=world,proto3" json:"world,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceWorldSnapshotResponse) Reset() {
	*x = ReplaceWorldSnapshotResponse{}
	mi := &file_proto_world_v1_world_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceWorldSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceWorldSnapshotResponse) ProtoMessage() {}

func (x *ReplaceWorldSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceWorldSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ReplaceWorldSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{8}
}

func (x *ReplaceWorldSnapshotResponse) GetWorld() *World {
	if x != nil {
		return x.World
	}
	return nil
}

type DeleteWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorldRequest) Reset() {
	*x = DeleteWorldRequest{}
	mi := &file_proto_world_v1_world_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorldRequest) ProtoMessage() {}

func (x *DeleteWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorldRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorldRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteWorldRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWorldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorldResponse) Reset() {
	*x = DeleteWorldResponse{}
	mi := &file_proto_world_v1_world_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorldResponse) ProtoMessage() {}

func (x *DeleteWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorldResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorldResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{10}
}

type ListWorldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorldsRequest) Reset() {
	*x = ListWorldsRequest{}
	mi := &file_proto_world_v1_world_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorldsRequest) ProtoMessage() {}

func (x *ListWorldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorldsRequest.ProtoReflect.Descriptor instead.
func (*ListWorldsRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{11}
}

func (x *ListWorldsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWorldsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListWorldsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worlds        []*World               `protobuf:"bytes,1,rep,name=worlds,proto3" json:"worlds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorldsResponse) Reset() {
	*x = ListWorldsResponse{}
	mi := &file_proto_world_v1_world_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorldsResponse) ProtoMessage() {}

func (x *ListWorldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_v1_world_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorldsResponse.ProtoReflect.Descriptor instead.
func (*ListWorldsResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_v1_world_proto_rawDescGZIP(), []int{12}
}

func (x *ListWorldsResponse) GetWorlds() []*World {
	if x != nil {
		return x.Worlds
	}
	return nil
}

var File_proto_world_v1_world_proto protoreflect.FileDescriptor

const file_proto_world_v1_world_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/world/v1/world.proto\x12\bworld.v1\"\xfa\x01\n" +
	"\x05World\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bsnapshot\x18\x04 \x01(\fR\bsnapshot\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\x05R\rschemaVersion\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12&\n" +
	"\x0fcreated_at_unix\x18\a \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\b \x01(\x03R\rupdatedAtUnix\"\x9d\x01\n" +
	"\x12CreateWorldRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bsnapshot\x18\x04 \x01(\fR\bsnapshot\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\x05R\rschemaVersion\"<\n" +
	"\x13CreateWorldResponse\x12%\n" +
	"\x05world\x18\x01 \x01(\v2\x0f.world.v1.WorldR\x05world\"!\n" +
	"\x0fGetWorldRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x10GetWorldResponse\x12%\n" +
	"\x05world\x18\x01 \x01(\v2\x0f.world.v1.WorldR\x05world\"+\n" +
	"\x15GetWorldByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"?\n" +
	"\x16GetWorldByNameResponse\x12%\n" +
	"\x05world\x18\x01 \x01(\v2\x0f.world.v1.WorldR\x05world\"\x9b\x01\n" +
	"\x1bReplaceWorldSnapshotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsnapshot\x18\x02 \x01(\fR\bsnapshot\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\x05R\rschemaVersion\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x03R\x0fexpectedVersion\"E\n" +
	"\x1cReplaceWorldSnapshotResponse\x12%\n" +
	"\x05world\x18\x01 \x01(\v2\x0f.world.v1.WorldR\x05world\"$\n" +
	"\x12DeleteWorldRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteWorldResponse\"A\n" +
	"\x11ListWorldsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"=\n" +
	"\x12ListWorldsResponse\x12'\n" +
	"\x06worlds\x18\x01 \x03(\v2\x0f.world.v1.WorldR\x06worlds2\xee\x03\n" +
	"\fWorldService\x12J\n" +
	"\vCreateWorld\x12\x1c.world.v1.CreateWorldRequest\x1a\x1d.world.v1.CreateWorldResponse\x12A\n" +
	"\bGetWorld\x12\x19.world.v1.GetWorldRequest\x1a\x1a.world.v1.GetWorldResponse\x12S\n" +
	"\x0eGetWorldByName\x12\x1f.world.v1.GetWorldByNameRequest\x1a .world.v1.GetWorldByNameResponse\x12e\n" +
	"\x14ReplaceWorldSnapshot\x12%.world.v1.ReplaceWorldSnapshotRequest\x1a&.world.v1.ReplaceWorldSnapshotResponse\x12J\n" +
	"\vDeleteWorld\x12\x1c.world.v1.DeleteWorldRequest\x1a\x1d.world.v1.DeleteWorldResponse\x12G\n" +
	"\n" +
	"ListWorlds\x12\x1b.world.v1.ListWorldsRequest\x1a\x1c.world.v1.ListWorldsResponseB\x1eZ\x1cworld/proto/world/v1;worldv1b\x06proto3"

var (
	file_proto_world_v1_world_proto_rawDescOnce sync.Once
	file_proto_world_v1_world_proto_rawDescData []byte
)

func file_proto_world_v1_world_proto_rawDescGZIP() []byte {
	file_proto_world_v1_world_proto_rawDescOnce.Do(func() {
		file_proto_world_v1_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_world_v1_world_proto_rawDesc), len(file_proto_world_v1_world_proto_rawDesc)))
	})
	return file_proto_world_v1_world_proto_rawDescData
}

var file_proto_world_v1_world_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_world_v1_world_proto_goTypes = []any{
	(*World)(nil),                        // 0: world.v1.World
	(*CreateWorldRequest)(nil),           // 1: world.v1.CreateWorldRequest
	(*CreateWorldResponse)(nil),          // 2: world.v1.CreateWorldResponse
	(*GetWorldRequest)(nil),              // 3: world.v1.GetWorldRequest
	(*GetWorldResponse)(nil),             // 4: world.v1.GetWorldResponse
	(*GetWorldByNameRequest)(nil),        // 5: world.v1.GetWorldByNameRequest
	(*GetWorldByNameResponse)(nil),       // 6: world.v1.GetWorldByNameResponse
	(*ReplaceWorldSnapshotRequest)(nil),  // 7: world.v1.ReplaceWorldSnapshotRequest
	(*ReplaceWorldSnapshotResponse)(nil), // 8: world.v1.ReplaceWorldSnapshotResponse
	(*DeleteWorldRequest)(nil),           // 9: world.v1.DeleteWorldRequest
	(*DeleteWorldResponse)(nil),          // 10: world.v1.DeleteWorldResponse
	(*ListWorldsRequest)(nil),            // 11: world.v1.ListWorldsRequest
	(*ListWorldsResponse)(nil),           // 12: world.v1.ListWorldsResponse
}
var file_proto_world_v1_world_proto_depIdxs = []int32{
	0,  // 0: world.v1.CreateWorldResponse.world:type_name -> world.v1.World
	0,  // 1: world.v1.GetWorldResponse.world:type_name -> world.v1.World
	0,  // 2: world.v1.GetWorldByNameResponse.world:type_name -> world.v1.World
	0,  // 3: world.v1.ReplaceWorldSnapshotResponse.world:type_name -> world.v1.World
	0,  // 4: world.v1.ListWorldsResponse.worlds:type_name -> world.v1.World
	1,  // 5: world.v1.WorldService.CreateWorld:input_type -> world.v1.CreateWorldRequest
	3,  // 6: world.v1.WorldService.GetWorld:input_type -> world.v1.GetWorldRequest
	5,  // 7: world.v1.WorldService.GetWorldByName:input_type -> world.v1.GetWorldByNameRequest
	7,  // 8: world.v1.WorldService.ReplaceWorldSnapshot:input_type -> world.v1.ReplaceWorldSnapshotRequest
	9,  // 9: world.v1.WorldService.DeleteWorld:input_type -> world.v1.DeleteWorldRequest
	11, // 10: world.v1.WorldService.ListWorlds:input_type -> world.v1.ListWorldsRequest
	2,  // 11: world.v1.WorldService.CreateWorld:output_type -> world.v1.CreateWorldResponse
	4,  // 12: world.v1.WorldService.GetWorld:output_type -> world.v1.GetWorldResponse
	6,  // 13: world.v1.WorldService.GetWorldByName:output_type -> world.v1.GetWorldByNameResponse
	8,  // 14: world.v1.WorldService.ReplaceWorldSnapshot:output_type -> world.v1.ReplaceWorldSnapshotResponse
	10, // 15: world.v1.WorldService.DeleteWorld:output_type -> world.v1.DeleteWorldResponse
	12, // 16: world.v1.WorldService.ListWorlds:output_type -> world.v1.ListWorldsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_world_v1_world_proto_init() }
func file_proto_world_v1_world_proto_init() {
	if File_proto_world_v1_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_world_v1_world_proto_rawDesc), len(file_proto_world_v1_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_world_v1_world_proto_goTypes,
		DependencyIndexes: file_proto_world_v1_world_proto_depIdxs,
		MessageInfos:      file_proto_world_v1_world_proto_msgTypes,
	}.Build()
	File_proto_world_v1_world_proto = out.File
	file_proto_world_v1_world_proto_goTypes = nil
	file_proto_world_v1_world_proto_depIdxs = nil
}
